[package]
name = "chameo-privacy"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "chameo_privacy"

[dependencies]
anchor-lang = "0.30.1"
inco-lightning = "0.1.0"

[features]
default = []
